In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
dataset = dataset.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
dataset

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
gender_encoder = LabelEncoder()
dataset['Gender'] = gender_encoder.fit_transform(dataset['Gender'])
dataset

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [5]:
from sklearn.preprocessing import OneHotEncoder
geography_encoder = OneHotEncoder()
geography_encoded = geography_encoder.fit_transform(dataset[['Geography']])
geography_encoded_df = pd.DataFrame(geography_encoded.toarray(), columns=geography_encoder.get_feature_names_out(['Geography']))
dataset = pd.concat([dataset, geography_encoded_df], axis=1)
dataset = dataset.drop('Geography', axis=1)
dataset

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

CreditScore  Gender  Age  Tenure  Balance    NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  Geography_France  Geography_Germany  Geography_Spain
619          0       42   2       0.00       1              1          1               101348.88        1       1.0               0.0                0.0                1
608          0       41   1       83807.86   1              0          1               112542.58        0       0.0               0.0                1.0                1
502          0       42   8       159660.80  3              1          0               113931.57        1       1.0               0.0                0.0                1
699          0       39   1       0.00       2              0          0               93826.63         0       1.0               0.0                0.0                1
850          0       43   2       125510.82  1              1          1               79084.10         0       0.0               0.0                1.0                1
                                                                                                                                                                       ..
771          1       39   5       0.00       2              1          0               96270.64         0       1.0               0.0                0.0                1
516          1       35   10      57369.61   1              1          1               101699.77        0       1.0               0.0                0.0                1
709          0       36   7       0.00       1              0          1               42085.58         1       1.0               0.0                0.0                1
772          1       42   3       75075.31   2              1          0               92888.52         1       0.0               1.0                0.0                1
792          0       28   4       130142.79  1              1          0               38190.78         0       1.0               0.0                0.0                1
Name: count, Length: 10000, dtype: int64

In [14]:
## Save the encoders for later use
with open('gender_encoder.pkl', 'wb') as f:
    pickle.dump(gender_encoder, f)

with open('geography_encoder.pkl', 'wb') as f:
    pickle.dump(geography_encoder, f)

In [17]:
x= dataset.drop('Exited', axis=1)
y= dataset['Exited']
x, y

(      CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
 0             619       0   42       2       0.00              1          1
 1             608       0   41       1   83807.86              1          0
 2             502       0   42       8  159660.80              3          1
 3             699       0   39       1       0.00              2          0
 4             850       0   43       2  125510.82              1          1
 ...           ...     ...  ...     ...        ...            ...        ...
 9995          771       1   39       5       0.00              2          1
 9996          516       1   35      10   57369.61              1          1
 9997          709       0   36       7       0.00              1          0
 9998          772       1   42       3   75075.31              2          1
 9999          792       0   28       4  130142.79              1          1

       IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
 0                  1        101348.88               1.0                0.0
 1                  1        112542.58               0.0                0.0
 2                  0        113931.57               1.0                0.0
 3                  0         93826.63               1.0                0.0
 4                  1         79084.10               0.0                0.0
 ...              ...              ...               ...                ...
 9995               0         96270.64               1.0                0.0
 9996               1        101699.77               1.0                0.0
 9997               1         42085.58               1.0                0.0
 9998               0         92888.52               0.0                1.0
 9999               0         38190.78               1.0                0.0

       Geography_Spain
 0                 0.0
 1                 1.0
 2                 0.0
 3                 0.0
 4                 1.0
 ...               ...
 9995              0.0
 9996              0.0
 9997              0.0
 9998              0.0
 9999              0.0

 [10000 rows x 12 columns],
 0       1
 1       0
 2       1
 3       0
 4       0
        ..
 9995    0
 9996    0
 9997    1
 9998    1
 9999    0
 Name: Exited, Length: 10000, dtype: int64)

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [20]:
## save the scaler for later use
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

## ANN Implementation

In [21]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [22]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(x_train_scaled.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])
model.summary()

d:\Study Materials\Python\Learning\myenv312\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [23]:
## Compile the model
adam_opt = tf.keras.optimizers.Adam(learning_rate=0.001)
loss_fn = tf.keras.losses.BinaryCrossentropy()
model.compile(optimizer=adam_opt, loss=loss_fn, metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [26]:
## Set up tensorboard callback
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [27]:
## Set up early stopping callback
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [28]:
## Train the model
history = model.fit(x_train_scaled, y_train, validation_data=(x_test_scaled, y_test), epochs=50, callbacks=[tensorboard_callback, early_stopping_callback])

Epoch 1/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.7904 - loss: 0.4639 - val_accuracy: 0.8380 - val_loss: 0.3879
Epoch 2/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8457 - loss: 0.3811 - val_accuracy: 0.8560 - val_loss: 0.3525
Epoch 3/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8561 - loss: 0.3535 - val_accuracy: 0.8620 - val_loss: 0.3446
Epoch 4/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8594 - loss: 0.3458 - val_accuracy: 0.8595 - val_loss: 0.3422
Epoch 5/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8599 - loss: 0.3409 - val_accuracy: 0.8615 - val_loss: 0.3467
Epoch 6/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8586 - loss: 0.3380 - val_accuracy: 0.8615 - val_loss: 0.3437
Epoch 7/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8654 - loss: 0.3349 - val_accuracy: 0.8615 - val_loss: 0.3420
Epoch 8/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8630 - loss: 0.3326 - val_accuracy: 0.8625 - val_loss: 0.3410
Epoch 9/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8633 - loss: 0.3302 - val_accuracy: 0.8635 - val_loss: 0.3427
Epoch 10/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8683 - loss: 0.3271 - val_accuracy: 0.8560 - val_loss: 0.3440
Epoch 11/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8658 - loss: 0.3254 - val_accuracy: 0.8600 - val_loss: 0.3431
Epoch 12/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8648 - loss: 0.3236 - val_accuracy: 0.8625 - val_loss: 0.3447
Epoch 13/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8684 - loss: 0.3223 - val_accuracy: 0.8670 - val_loss: 0.3397
Epoch 14/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8662 - loss: 0.3204 - val_accuracy: 0.8665 - val_loss: 0.3396
Epoch 15/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8705 - loss: 0.3183 - val_accuracy: 0.8570 - val_loss: 0.3520
Epoch 16/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8661 - loss: 0.3195 - val_accuracy: 0.8630 - val_loss: 0.3407
Epoch 17/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8671 - loss: 0.3156 - val_accuracy: 0.8595 - val_loss: 0.3454
Epoch 18/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8702 - loss: 0.3140 - val_accuracy: 0.8625 - val_loss: 0.3440
Epoch 19/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8701 - loss: 0.3137 - val_accuracy: 0.8575 - val_loss: 0.3426

In [29]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [30]:
## load tensorboard extension
%load_ext tensorboard
%tensorboard --logdir logs/fit

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Study Materials\Python\Learning\myenv312\Scripts\tensorboard.exe\__main__.py", line 2, in <module>
  File "D:\Study Materials\Python\Learning\myenv312\Lib\site-packages\tensorboard\main.py", line 27, in <module>
    from tensorboard import default
  File "D:\Study Materials\Python\Learning\myenv312\Lib\site-packages\tensorboard\default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'