In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import numpy as np
import pandas as pd

In [2]:
## load the model
model = load_model('model.h5')
## load the scaler
with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)
## load the gender encoder
with open('gender_encoder.pkl', 'rb') as f:
    gender_encoder = pickle.load(f)
## load the geography encoder
with open('geography_encoder.pkl', 'rb') as f:
    geography_encoder = pickle.load(f)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [9]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

# Convert input data to DataFrame
input_df = pd.DataFrame([input_data])

# Encode categorical features
input_df['Gender'] = gender_encoder.transform(input_df['Gender'])

input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [10]:
input_geography_encoded = geography_encoder.transform(input_df[['Geography']])
input_df = input_df.drop('Geography', axis=1)
input_df = pd.concat([input_df, pd.DataFrame(input_geography_encoded.toarray(), columns=geography_encoder.get_feature_names_out(['Geography']))], axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [11]:
input_scaled = scaler.transform(input_df)
prediction = model.predict(input_scaled)
print(f'Predicted probability of churn: {prediction[0][0]:.4f}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 594ms/step
Predicted probability of churn: 0.0204