In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
gender_encoder = LabelEncoder()
data['Gender'] = gender_encoder.fit_transform(data['Gender'])

In [5]:
geography_encoder = OneHotEncoder(handle_unknown='ignore')
geography_encoded = geography_encoder.fit_transform(data[['Geography']])
data = pd.concat([data, pd.DataFrame(geography_encoded.toarray(), columns=geography_encoder.get_feature_names_out(['Geography']))], axis=1)
data = data.drop('Geography', axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [6]:
x = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

## ANN Regression Problem Statement

In [8]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
model = Sequential([
    Dense(64, activation='elu', input_shape=(x_train_scaled.shape[1],)),
    Dense(32, activation='elu'),
    Dense(1)
])

model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

model.summary()

d:\Study Materials\Python\Learning\myenv312\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# set up tensorboard callback
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [11]:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [14]:
history = model.fit(x_train_scaled, y_train, validation_data=(x_test_scaled, y_test), epochs=50, callbacks=[tensorboard_callback, early_stopping_callback])

Epoch 1/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 100407.0547 - mae: 100407.0547 - val_loss: 98633.2656 - val_mae: 98633.2656
Epoch 2/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100027.2812 - mae: 100027.2812 - val_loss: 97800.8672 - val_mae: 97800.8672
Epoch 3/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 98504.3047 - mae: 98504.3047 - val_loss: 95516.7031 - val_mae: 95516.7031
Epoch 4/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 95429.2422 - mae: 95429.2422 - val_loss: 91628.2188 - val_mae: 91628.2188
Epoch 5/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 90894.5625 - mae: 90894.5625 - val_loss: 86508.8672 - val_mae: 86508.8672
Epoch 6/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 85400.2031 - mae: 85400.2031 - val_loss: 80841.4766 - val_mae: 80841.4766
Epoch 7/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 79598.1953 - mae: 79598.1953 - val_loss: 75418.8203 - val_mae: 75418.8203
Epoch 8/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 74442.4375 - mae: 74442.4375 - val_loss: 70936.1797 - val_mae: 70936.1797
Epoch 9/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 70429.5703 - mae: 70429.5703 - val_loss: 67643.6953 - val_mae: 67643.6953
Epoch 10/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 67694.3516 - mae: 67694.3516 - val_loss: 65432.3828 - val_mae: 65432.3828
Epoch 11/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 65904.3984 - mae: 65904.3984 - val_loss: 64159.8086 - val_mae: 64159.8086
Epoch 12/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 64731.1172 - mae: 64731.1172 - val_loss: 63400.7930 - val_mae: 63400.7930
Epoch 13/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 64001.4648 - mae: 64001.4648 - val_loss: 62905.3633 - val_mae: 62905.3633
Epoch 14/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 63558.9727 - mae: 63558.9727 - val_loss: 62634.8047 - val_mae: 62634.8047
Epoch 15/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63271.8867 - mae: 63271.8867 - val_loss: 62457.1328 - val_mae: 62457.1328
Epoch 16/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 63076.0039 - mae: 63076.0039 - val_loss: 62321.0977 - val_mae: 62321.0977
Epoch 17/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62937.3008 - mae: 62937.3008 - val_loss: 62216.1328 - val_mae: 62216.1328
Epoch 18/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62837.1328 - mae: 62837.1328 - val_loss: 62141.5781 - val_mae: 62141.5781
Epoch 19/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 62757.0195 - mae: 62757.0195 - val_loss: 62080.6680 - val_mae: 62080.6680
Epoch 20/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 62702.2148 - mae: 62702.2148 - val_loss: 62049.2109 - val_mae: 62049.2109
Epoch 21/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 62653.5195 - mae: 62653.5195 - val_loss: 62019.2695 - val_mae: 62019.2695
Epoch 22/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 62614.3828 - mae: 62614.3828 - val_loss: 61993.8008 - val_mae: 61993.8008
Epoch 23/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62582.8281 - mae: 62582.8281 - val_loss: 61975.5742 - val_mae: 61975.5742
Epoch 24/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62554.5117 - mae: 62554.5117 - val_loss: 61940.0156 - val_mae: 61940.0156
Epoch 25/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62535.5352 - mae: 62535.5352 - val_loss: 61932.2773 - val_mae: 61932.2773
Epoch 26/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62515.6914 - mae: 62515.6914 - val_loss: 61921.6055 - val_mae: 61921.6055
Epoch 27/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62499.1055 - mae: 62499.1055 - val_loss: 61911.2539 - val_mae: 61911.2539
Epoch 28/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62485.7695 - mae: 62485.7695 - val_loss: 61903.2578 - val_mae: 61903.2578
Epoch 29/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62476.4531 - mae: 62476.4531 - val_loss: 61882.7734 - val_mae: 61882.7734
Epoch 30/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62470.4844 - mae: 62470.4844 - val_loss: 61881.0156 - val_mae: 61881.0156
Epoch 31/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 62456.8711 - mae: 62456.8711 - val_loss: 61881.2148 - val_mae: 61881.2148
Epoch 32/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 62448.8359 - mae: 62448.8359 - val_loss: 61870.9648 - val_mae: 61870.9648
Epoch 33/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 62446.8711 - mae: 62446.8711 - val_loss: 61876.8320 - val_mae: 61876.8320
Epoch 34/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62440.6758 - mae: 62440.6758 - val_loss: 61871.1016 - val_mae: 61871.1016
Epoch 35/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62436.7656 - mae: 62436.7656 - val_loss: 61863.1016 - val_mae: 61863.1016
Epoch 36/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62434.5469 - mae: 62434.5469 - val_loss: 61866.3516 - val_mae: 61866.3516
Epoch 37/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62431.8281 - mae: 62431.8281 - val_loss: 61867.2070 - val_mae: 61867.2070
Epoch 38/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62426.3516 - mae: 62426.3516 - val_loss: 61889.8047 - val_mae: 61889.8047
Epoch 39/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62425.8398 - mae: 62425.8398 - val_loss: 61874.3164 - val_mae: 61874.3164
Epoch 40/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62424.6914 - mae: 62424.6914 - val_loss: 61868.3086 - val_mae: 61868.3086
Epoch 41/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62421.4023 - mae: 62421.4023 - val_loss: 61878.3633 - val_mae: 61878.3633
Epoch 42/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62417.6094 - mae: 62417.6094 - val_loss: 61883.6406 - val_mae: 61883.6406
Epoch 43/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62423.2305 - mae: 62423.2305 - val_loss: 61877.0938 - val_mae: 61877.0938
Epoch 44/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62412.7461 - mae: 62412.7461 - val_loss: 61861.9648 - val_mae: 61861.9648
Epoch 45/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 62414.5195 - mae: 62414.5195 - val_loss: 61869.2266 - val_mae: 61869.2266
Epoch 46/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62412.6016 - mae: 62412.6016 - val_loss: 61856.8359 - val_mae: 61856.8359
Epoch 47/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 62412.9531 - mae: 62412.9531 - val_loss: 61870.3867 - val_mae: 61870.3867
Epoch 48/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 62406.2930 - mae: 62406.2930 - val_loss: 61879.9883 - val_mae: 61879.9883
Epoch 49/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 62408.6055 - mae: 62408.6055 - val_loss: 61892.7852 - val_mae: 61892.7852
Epoch 50/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 62402.3125 - mae: 62402.3125 - val_loss: 61876.0195 - val_mae: 61876.0195

In [15]:
%load_ext tensorboard
%tensorboard --logdir logs/fit

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Study Materials\Python\Learning\myenv312\Scripts\tensorboard.exe\__main__.py", line 2, in <module>
  File "D:\Study Materials\Python\Learning\myenv312\Lib\site-packages\tensorboard\main.py", line 27, in <module>
    from tensorboard import default
  File "D:\Study Materials\Python\Learning\myenv312\Lib\site-packages\tensorboard\default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

In [16]:
## Evaluate the model
test_loss, test_mae = model.evaluate(x_test_scaled, y_test)
print(f'Test MAE: {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 61856.8359 - mae: 61856.8359
Test MAE: 61856.8359375

In [17]:
# Save the model
model.save('salary_regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.